### ISSUE TITLE
Zygomys in Production

### ISSUE THREAD

**Issue by dc0d** [glycerine/zygomys#17]
Is Zygomys being used in production? Who is using it?

Sorry to ask here; but I did not get any meaningful responses from other places.

**Comment by glycerine** [comment]
@dc0d No worries. I haven't heard of anyone using it in production.

The byte code interpreter is pretty slow compared to most languages; it isn't very optimized.

I haven't worked on zygomys in a while.  There is not a big community of users. I can offer some advice, but if you need extensions or issue fixes, you are going to be doing them yourself.

If you were going to write your own interpreter or interactive REPL anyway, it's a pretty nice play to start.
