### ISSUE TITLE
repl package should be called zygo

### ISSUE THREAD

**Issue by briansorahan** [glycerine/zygomys#20]
I found it confusing how I might get the Go API examples to work. I didn't see a zygo package anywhere in the repo. Finally found that it was repl by looking at cmd/zygo/main.go

This is just a suggestion, but it's a convention the Go community has largely adopted https://golang.org/doc/effective_go.html#package-names

**Comment by glycerine** [comment]
I dislike the stuttering of zygomys/zygo, hence my preference for repl; its also more descriptive of its role when embedded.
