### ISSUE TITLE
Hook Syntax

### ISSUE THREAD

**Issue by ejemba** [glycerine/zygomys#3]
Can you just give a sample for the hook (Pre and Post) in the wiki ?

PS 
Thank you for this amazing lib !

**Comment by glycerine** [comment]
Thanks @ejemba :) 

The hooks are for Go functions. For example, see `CountPreHook` and `CountPostHook` 

https://github.com/glycerine/zygomys/blob/01562f6161e20b70040704f1c805e3e64af4ede7/repl/repl.go#L16

and

https://github.com/glycerine/zygomys/blob/01562f6161e20b70040704f1c805e3e64af4ede7/repl/repl.go#L392

I'll leave this open as a reminder to add a description to the wiki in the near future.

**Comment by glycerine** [comment]
Thinking on this a little more, the hooks are mostly a means of internal profiling, left over from the Glisp days. I removed them from the feature list just now. They are still there internally, but not really meant to support anything vis-a-vis the language itself.  So I'm closing this out as an (intentinoally undocumented and unsupported feature; any user of the library can do similar or even simpler profiling trivially.

**Comment by ejemba** [comment]
@glycerine thank you for your answer :) I was thinking of them like the advice in emacs-lisp 
defadvice or hook that are very usefull.

Thanks anyway :)

**Comment by glycerine** [comment]
@ejemba wow I had no idea emacs lisp had all that. It's so built out. Kind of amazing. Glad you mentioned it(!)
