### ISSUE TITLE
Missing function for milliseconds

### ISSUE THREAD

**Issue by jkleiser** [glycerine/zygomys#35]
I see that zygo has time related functions like `now`, `astm` and `timeit`, but I cannot find any function returning milliseconds since some fixed time (1970-01-01), or since zygo launch. Floating point seconds with decimals could also do.

**Comment by glycerine** [comment]
Reasonable. Would you kindly send a pull request?

https://github.com/glycerine/zygomys/blob/master/zygo/time.go is probably the best place to add such things.

**Comment by jkleiser** [comment]
I will give it a try. Maybe later this week.

**Comment by glycerine** [comment]
>unixmillis or just millis?

your call, but I like the shorter name

> In the file cmd/zygo/main.go, line 9, I had to change the import to "github.com/jkleiser/zygomys/zygo". Is there a way to write this to avoid it being so github specific?

not that I'm aware of. If you file a PR though, leave it pointing at glycerine/zygomys so the project still builds by default with a `go get`.

**Comment by jkleiser** [comment]
Agreed on "millis".
