### ISSUE TITLE
Error message that could have been better

### ISSUE THREAD

**Issue by jkleiser** [glycerine/zygomys#37]
If I type `(foo)`, I get this message:
```
error in evalGeneratedFunction:0: Error calling 'infix': symbol `foo` not found
in infix:0
in __main:34
```
This is not a very "friendly" error message. Why all the mention of "infix"? The main message here should be "symbol 'foo' not defined".

**Comment by jkleiser** [comment]
I see this mention of "infix" occurs in other error messages too, e.g. this:
```
error in aset:-1: Error calling 'infix': Error calling 'aset': Array index out of bounds
```
Maybe the "infix" function could have another name?

**Comment by glycerine** [comment]
The message is apt, as the infix parser is the active one.
