### ISSUE TITLE
[Feature request] Unsigned integers

### ISSUE THREAD

**Issue by japanoise** [glycerine/zygomys#39]
I'd like to use Zygomys for my assembler project. I notice that it's documented to only use signed `int64`s; it'd be useful if I could use unsigned integers in some way, preferably as `uint64`s.

**Comment by glycerine** [comment]
Sure; this isn't too difficult. Just add an SexpUint64 to match the SexpInt everywhere; see https://github.com/glycerine/zygomys/blob/master/zygo/expressions.go#L72 for the definition of SexpInt.

You'll need to add this yourself. But I'm happy to review and merge a PR. You'll need a testfile under tests/uint.zy.

**Comment by glycerine** [comment]
@japanoise The latest release, v5.0.9, has uint64 support. See the tests/uint64.zy file for examples.

Try this out and let me know if there's anything significant missing to make it usable.

**Comment by glycerine** [comment]
Closing this as now implemented. Feel free to open a new issue for any refinements.

**Comment by japanoise** [comment]
Thank you for the quick turnaround!
