### ISSUE TITLE
Is there an intelligent prompt ide or plug-in to support grammar?

### ISSUE THREAD

**Issue by aadog** [glycerine/zygomys#45]
Is there an intelligent prompt ide or plug-in to support grammar?

**Comment by glycerine** [comment]
There is not. Pull requests welcome, of course.

https://github.com/glycerine/zygomys/blob/master/zygo/liner.go#L11  shows the tab completion machinery that is installed, which is limited. Mostly LISP grammar is incredibly uniform, it is learned very quickly.  I do recommend emacs for the electric brace functionality and general LISP friendliness it provides.

**Comment by a97077088** [comment]
I will pay close attention to your project and see how the smarttip plugin is progressing. I think it is already rich enough. Why is it not compatible with Goland's smart tips? I think this will be liked by many people.

**Comment by lthibault** [comment]
@glycerine I'm considering zygomys for a project of mine.  I've been wanting to dive into language design for a while now, and I think building this kind of feature might be a good jumping-off point for me.

Would you be generally available to help me out if I were to undertake this?

**Comment by glycerine** [comment]
@lthibault Hi Louis, lisp has almost no grammar, just prefix forms, so this "feature" makes no sense to me. Hence I cannot recommend it.  I don't see the goal or idea.  More importantly, it doesn't do anything towards your goal of learning about language design.

**Comment by lthibault** [comment]
@glycerine Fair point -- thanks for the candid feedback (seriously, you just helped me avoid a potential rabbit-hole)!
